//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFNZ_HPD_IncidentInterface_Mod_UAT
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", ConfigurationName="VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType")]
    public interface HPD_IncidentInterface_WSPortTypePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:VFNZ_HPD_IncidentInterface_Mod_WS/HelpDesk_Resolve_Incident", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Resolve_IncidentResponse> HelpDesk_Resolve_IncidentAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Resolve_IncidentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:VFNZ_HPD_IncidentInterface_Mod_WS/HelpDesk_Relate_CI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Relate_CIResponse> HelpDesk_Relate_CIAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Relate_CIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:VFNZ_HPD_IncidentInterface_Mod_WS/HelpDesk_Update_Summary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Update_SummaryResponse> HelpDesk_Update_SummaryAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Update_SummaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:VFNZ_HPD_IncidentInterface_Mod_WS/HelpDesk_Assign_Incident", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Assign_IncidentResponse> HelpDesk_Assign_IncidentAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Assign_IncidentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:VFNZ_HPD_IncidentInterface_Mod_WS/HelpDesk_Set_ProdCat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Set_ProdCatResponse> HelpDesk_Set_ProdCatAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Set_ProdCatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:VFNZ_HPD_IncidentInterface_Mod_WS/HelpDesk_Add_WorkInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Add_WorkInfoResponse> HelpDesk_Add_WorkInfoAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Add_WorkInfoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS")]
    public partial class AuthenticationInfo
    {
        
        private string userNameField;
        
        private string passwordField;
        
        private string authenticationField;
        
        private string localeField;
        
        private string timeZoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string authentication
        {
            get
            {
                return this.authenticationField;
            }
            set
            {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string timeZone
        {
            get
            {
                return this.timeZoneField;
            }
            set
            {
                this.timeZoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS")]
    public enum InterfaceActionType
    {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        IntegrationResponse,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Integration Timeout")]
        IntegrationTimeout,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Create Incident")]
        CreateIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Update Incident")]
        UpdateIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resolve Incident")]
        ResolveIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Status Change Incident")]
        StatusChangeIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Create Workinfo for Incident")]
        CreateWorkinfoforIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Create WorkOrder")]
        CreateWorkOrder,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Update WorkOrder")]
        UpdateWorkOrder,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Complete WorkOrder")]
        CompleteWorkOrder,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Status Change WorkOrder")]
        StatusChangeWorkOrder,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Create WorkInfo for WorkOrder")]
        CreateWorkInfoforWorkOrder,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS")]
    public enum StatusType
    {
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Assigned,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("In Progress")]
        InProgress,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Resolved,
        
        /// <remarks/>
        Closed,
        
        /// <remarks/>
        Cancelled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS")]
    public enum Status_ReasonType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Change Created")]
        InfrastructureChangeCreated,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Local Site Action Required")]
        LocalSiteActionRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Purchase Order Approval")]
        PurchaseOrderApproval,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Registration Approval")]
        RegistrationApproval,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Supplier Delivery")]
        SupplierDelivery,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Support Contact Hold")]
        SupportContactHold,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Third Party Vendor Action Reqd")]
        ThirdPartyVendorActionReqd,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Client Action Required")]
        ClientActionRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Change")]
        InfrastructureChange,
        
        /// <remarks/>
        Request,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Future Enhancement")]
        FutureEnhancement,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pending Original Incident")]
        PendingOriginalIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Client Hold")]
        ClientHold,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Monitoring Incident")]
        MonitoringIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Follow-Up Required")]
        CustomerFollowUpRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Temporary Corrective Action")]
        TemporaryCorrectiveAction,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("No Further Action Required")]
        NoFurtherActionRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resolved by Original Incident")]
        ResolvedbyOriginalIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Automated Resolution Reported")]
        AutomatedResolutionReported,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("No longer a Causal CI")]
        NolongeraCausalCI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS")]
    public enum Work_Info_TypeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- Customer Inbound -----")]
        CustomerInbound,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Communication")]
        CustomerCommunication,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Follow-up")]
        CustomerFollowup,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Status Update")]
        CustomerStatusUpdate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- Customer Outbound -----")]
        CustomerOutbound,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Closure Follow Up")]
        ClosureFollowUp,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Detail Clarification")]
        DetailClarification,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("General Information")]
        GeneralInformation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resolution Communications")]
        ResolutionCommunications,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Satisfaction Survey")]
        SatisfactionSurvey,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Status Update")]
        StatusUpdate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- General -----")]
        General,
        
        /// <remarks/>
        AlarmPoint,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Incident Task / Action")]
        IncidentTaskAction,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Problem Script")]
        ProblemScript,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Working Log")]
        WorkingLog,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Email System")]
        EmailSystem,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Paging System")]
        PagingSystem,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS")]
    public enum Work_Info_Communication_SourceType
    {
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        Phone,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Voice Mail")]
        VoiceMail,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Walk In")]
        WalkIn,
        
        /// <remarks/>
        Pager,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System Assignment")]
        SystemAssignment,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        Other,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("BMC Impact Manager Event")]
        BMCImpactManagerEvent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS")]
    public enum Work_Info_LockedType
    {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS")]
    public enum Work_Info_View_AccessType
    {
        
        /// <remarks/>
        Private,
        
        /// <remarks/>
        Public,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Resolve_Incident", WrapperNamespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", IsWrapped=true)]
    public partial class HelpDesk_Resolve_IncidentRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS")]
        public VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=0)]
        public string Incident_Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=1)]
        public string Direct_Contact_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=2)]
        public string Action_Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<InterfaceActionType> InterfaceAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=4)]
        public VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Status_ReasonType> Status_Reason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=6)]
        public string Work_Info_Notes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=7)]
        public string Work_Info_Summary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Work_Info_TypeType> Work_Info_Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> Work_Info_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Work_Info_Communication_SourceType> Work_Info_Communication_Source;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Work_Info_LockedType> Work_Info_Locked;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Work_Info_View_AccessType> Work_Info_View_Access;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Resolution;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cause;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Resolution_Method;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=16)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Resolution_Category_Tier_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=17)]
        public string Resolution_Category_Tier_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=18)]
        public string Resolution_Category_Tier_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=19)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Closure_Product_Category_Tier1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=20)]
        public string Closure_Product_Category_Tier2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=21)]
        public string Closure_Product_Category_Tier3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=22)]
        public string Closure_Product_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=23)]
        public string Closure_Product_Model_Version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=24)]
        public string Closure_Manufacturer;
        
        public HelpDesk_Resolve_IncidentRequest()
        {
        }
        
        public HelpDesk_Resolve_IncidentRequest(
                    VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo, 
                    string Incident_Number, 
                    string Direct_Contact_Company, 
                    string Action_Status, 
                    System.Nullable<InterfaceActionType> InterfaceAction, 
                    VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status, 
                    System.Nullable<Status_ReasonType> Status_Reason, 
                    string Work_Info_Notes, 
                    string Work_Info_Summary, 
                    System.Nullable<Work_Info_TypeType> Work_Info_Type,
                    System.Nullable<System.DateTime> Work_Info_Date, 
                    System.Nullable<Work_Info_Communication_SourceType> Work_Info_Communication_Source, 
                    System.Nullable<Work_Info_LockedType> Work_Info_Locked, 
                    System.Nullable<Work_Info_View_AccessType> Work_Info_View_Access, 
                    string Resolution, 
                    string Cause, 
                    string Resolution_Method, 
                    string Resolution_Category_Tier_1, 
                    string Resolution_Category_Tier_2, 
                    string Resolution_Category_Tier_3, 
                    string Closure_Product_Category_Tier1, 
                    string Closure_Product_Category_Tier2, 
                    string Closure_Product_Category_Tier3, 
                    string Closure_Product_Name, 
                    string Closure_Product_Model_Version, 
                    string Closure_Manufacturer)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.Incident_Number = Incident_Number;
            this.Direct_Contact_Company = Direct_Contact_Company;
            this.Action_Status = Action_Status;
            this.InterfaceAction = InterfaceAction;
            this.Status = Status;
            this.Status_Reason = Status_Reason;
            this.Work_Info_Notes = Work_Info_Notes;
            this.Work_Info_Summary = Work_Info_Summary;
            this.Work_Info_Type = Work_Info_Type;
            this.Work_Info_Date = Work_Info_Date;
            this.Work_Info_Communication_Source = Work_Info_Communication_Source;
            this.Work_Info_Locked = Work_Info_Locked;
            this.Work_Info_View_Access = Work_Info_View_Access;
            this.Resolution = Resolution;
            this.Cause = Cause;
            this.Resolution_Method = Resolution_Method;
            this.Resolution_Category_Tier_1 = Resolution_Category_Tier_1;
            this.Resolution_Category_Tier_2 = Resolution_Category_Tier_2;
            this.Resolution_Category_Tier_3 = Resolution_Category_Tier_3;
            this.Closure_Product_Category_Tier1 = Closure_Product_Category_Tier1;
            this.Closure_Product_Category_Tier2 = Closure_Product_Category_Tier2;
            this.Closure_Product_Category_Tier3 = Closure_Product_Category_Tier3;
            this.Closure_Product_Name = Closure_Product_Name;
            this.Closure_Product_Model_Version = Closure_Product_Model_Version;
            this.Closure_Manufacturer = Closure_Manufacturer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Resolve_IncidentResponse", WrapperNamespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", IsWrapped=true)]
    public partial class HelpDesk_Resolve_IncidentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=0)]
        public string Request_ID;
        
        public HelpDesk_Resolve_IncidentResponse()
        {
        }
        
        public HelpDesk_Resolve_IncidentResponse(string Request_ID)
        {
            this.Request_ID = Request_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Relate_CI", WrapperNamespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", IsWrapped=true)]
    public partial class HelpDesk_Relate_CIRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS")]
        public VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=0)]
        public string Incident_Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=1)]
        public string Direct_Contact_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=2)]
        public string Action_Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<InterfaceActionType> InterfaceAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=4)]
        public VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=5)]
        public string CI_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=6)]
        public string Lookup_Keyword;
        
        public HelpDesk_Relate_CIRequest()
        {
        }
        
        public HelpDesk_Relate_CIRequest(VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo, string Incident_Number, string Direct_Contact_Company, string Action_Status, System.Nullable<InterfaceActionType> InterfaceAction, VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status, string CI_Name, string Lookup_Keyword)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.Incident_Number = Incident_Number;
            this.Direct_Contact_Company = Direct_Contact_Company;
            this.Action_Status = Action_Status;
            this.InterfaceAction = InterfaceAction;
            this.Status = Status;
            this.CI_Name = CI_Name;
            this.Lookup_Keyword = Lookup_Keyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Relate_CIResponse", WrapperNamespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", IsWrapped=true)]
    public partial class HelpDesk_Relate_CIResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=0)]
        public string Request_ID;
        
        public HelpDesk_Relate_CIResponse()
        {
        }
        
        public HelpDesk_Relate_CIResponse(string Request_ID)
        {
            this.Request_ID = Request_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Update_Summary", WrapperNamespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", IsWrapped=true)]
    public partial class HelpDesk_Update_SummaryRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS")]
        public VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=0)]
        public string Incident_Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=1)]
        public string Direct_Contact_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=2)]
        public string Action_Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<InterfaceActionType> InterfaceAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=4)]
        public VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=5)]
        public string Summary;
        
        public HelpDesk_Update_SummaryRequest()
        {
        }
        
        public HelpDesk_Update_SummaryRequest(VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo, string Incident_Number, string Direct_Contact_Company, string Action_Status, System.Nullable<InterfaceActionType> InterfaceAction, VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status, string Summary)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.Incident_Number = Incident_Number;
            this.Direct_Contact_Company = Direct_Contact_Company;
            this.Action_Status = Action_Status;
            this.InterfaceAction = InterfaceAction;
            this.Status = Status;
            this.Summary = Summary;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Update_SummaryResponse", WrapperNamespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", IsWrapped=true)]
    public partial class HelpDesk_Update_SummaryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=0)]
        public string Request_ID;
        
        public HelpDesk_Update_SummaryResponse()
        {
        }
        
        public HelpDesk_Update_SummaryResponse(string Request_ID)
        {
            this.Request_ID = Request_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Assign_Incident", WrapperNamespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", IsWrapped=true)]
    public partial class HelpDesk_Assign_IncidentRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS")]
        public VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=0)]
        public string Incident_Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=1)]
        public string Direct_Contact_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=2)]
        public string Action_Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<InterfaceActionType> InterfaceAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=4)]
        public VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=5)]
        public string Assigned_Support_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=6)]
        public string Assigned_Support_Organization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=7)]
        public string Assigned_Group;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=8)]
        public string Assignee;
        
        public HelpDesk_Assign_IncidentRequest()
        {
        }
        
        public HelpDesk_Assign_IncidentRequest(VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo, string Incident_Number, string Direct_Contact_Company, string Action_Status, System.Nullable<InterfaceActionType> InterfaceAction, VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status, string Assigned_Support_Company, string Assigned_Support_Organization, string Assigned_Group, string Assignee)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.Incident_Number = Incident_Number;
            this.Direct_Contact_Company = Direct_Contact_Company;
            this.Action_Status = Action_Status;
            this.InterfaceAction = InterfaceAction;
            this.Status = Status;
            this.Assigned_Support_Company = Assigned_Support_Company;
            this.Assigned_Support_Organization = Assigned_Support_Organization;
            this.Assigned_Group = Assigned_Group;
            this.Assignee = Assignee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Assign_IncidentResponse", WrapperNamespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", IsWrapped=true)]
    public partial class HelpDesk_Assign_IncidentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=0)]
        public string Request_ID;
        
        public HelpDesk_Assign_IncidentResponse()
        {
        }
        
        public HelpDesk_Assign_IncidentResponse(string Request_ID)
        {
            this.Request_ID = Request_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Set_ProdCat", WrapperNamespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", IsWrapped=true)]
    public partial class HelpDesk_Set_ProdCatRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS")]
        public VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Incident_Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Direct_Contact_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=2)]
        public string Action_Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<InterfaceActionType> InterfaceAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=4)]
        public VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Product_Categorization_Tier_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=6)]
        public string Product_Categorization_Tier_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=7)]
        public string Product_Categorization_Tier_3;
        
        public HelpDesk_Set_ProdCatRequest()
        {
        }
        
        public HelpDesk_Set_ProdCatRequest(VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo, string Incident_Number, string Direct_Contact_Company, string Action_Status, System.Nullable<InterfaceActionType> InterfaceAction, VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status, string Product_Categorization_Tier_1, string Product_Categorization_Tier_2, string Product_Categorization_Tier_3)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.Incident_Number = Incident_Number;
            this.Direct_Contact_Company = Direct_Contact_Company;
            this.Action_Status = Action_Status;
            this.InterfaceAction = InterfaceAction;
            this.Status = Status;
            this.Product_Categorization_Tier_1 = Product_Categorization_Tier_1;
            this.Product_Categorization_Tier_2 = Product_Categorization_Tier_2;
            this.Product_Categorization_Tier_3 = Product_Categorization_Tier_3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Set_ProdCatResponse", WrapperNamespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", IsWrapped=true)]
    public partial class HelpDesk_Set_ProdCatResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=0)]
        public string Request_ID;
        
        public HelpDesk_Set_ProdCatResponse()
        {
        }
        
        public HelpDesk_Set_ProdCatResponse(string Request_ID)
        {
            this.Request_ID = Request_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Add_WorkInfo", WrapperNamespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", IsWrapped=true)]
    public partial class HelpDesk_Add_WorkInfoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS")]
        public VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Incident_Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=1)]
        public string Action_Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<InterfaceActionType> InterfaceAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=3)]
        public VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=4)]
        public string Work_Info_Notes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=5)]
        public string Work_Info_Summary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Work_Info_TypeType> Work_Info_Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=7)]
        public string Work_Info_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Work_Info_Communication_SourceType> Work_Info_Communication_Source;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Work_Info_LockedType> Work_Info_Locked;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Work_Info_View_AccessType> Work_Info_View_Access;
        
        public HelpDesk_Add_WorkInfoRequest()
        {
        }
        
        public HelpDesk_Add_WorkInfoRequest(VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo, string Incident_Number, string Action_Status, System.Nullable<InterfaceActionType> InterfaceAction, VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status, string Work_Info_Notes, string Work_Info_Summary, System.Nullable<Work_Info_TypeType> Work_Info_Type, string Work_Info_Date, System.Nullable<Work_Info_Communication_SourceType> Work_Info_Communication_Source, System.Nullable<Work_Info_LockedType> Work_Info_Locked, System.Nullable<Work_Info_View_AccessType> Work_Info_View_Access)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.Incident_Number = Incident_Number;
            this.Action_Status = Action_Status;
            this.InterfaceAction = InterfaceAction;
            this.Status = Status;
            this.Work_Info_Notes = Work_Info_Notes;
            this.Work_Info_Summary = Work_Info_Summary;
            this.Work_Info_Type = Work_Info_Type;
            this.Work_Info_Date = Work_Info_Date;
            this.Work_Info_Communication_Source = Work_Info_Communication_Source;
            this.Work_Info_Locked = Work_Info_Locked;
            this.Work_Info_View_Access = Work_Info_View_Access;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Add_WorkInfoResponse", WrapperNamespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", IsWrapped=true)]
    public partial class HelpDesk_Add_WorkInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:VFNZ_HPD_IncidentInterface_Mod_WS", Order=0)]
        public string Request_ID;
        
        public HelpDesk_Add_WorkInfoResponse()
        {
        }
        
        public HelpDesk_Add_WorkInfoResponse(string Request_ID)
        {
            this.Request_ID = Request_ID;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface HPD_IncidentInterface_WSPortTypePortTypeChannel : VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class HPD_IncidentInterface_WSPortTypePortTypeClient : System.ServiceModel.ClientBase<VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType>, VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HPD_IncidentInterface_WSPortTypePortTypeClient() : 
                base(HPD_IncidentInterface_WSPortTypePortTypeClient.GetDefaultBinding(), HPD_IncidentInterface_WSPortTypePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.HPD_IncidentInterface_WSPortTypeSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HPD_IncidentInterface_WSPortTypePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(HPD_IncidentInterface_WSPortTypePortTypeClient.GetBindingForEndpoint(endpointConfiguration), HPD_IncidentInterface_WSPortTypePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HPD_IncidentInterface_WSPortTypePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HPD_IncidentInterface_WSPortTypePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HPD_IncidentInterface_WSPortTypePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HPD_IncidentInterface_WSPortTypePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HPD_IncidentInterface_WSPortTypePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Resolve_IncidentResponse> VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType.HelpDesk_Resolve_IncidentAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Resolve_IncidentRequest request)
        {
            return base.Channel.HelpDesk_Resolve_IncidentAsync(request);
        }
        
        public System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Resolve_IncidentResponse> HelpDesk_Resolve_IncidentAsync(
                    VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo, 
                    string Incident_Number, 
                    string Direct_Contact_Company, 
                    string Action_Status, 
                    System.Nullable<InterfaceActionType> InterfaceAction, 
                    VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status, 
                    System.Nullable<Status_ReasonType> Status_Reason, 
                    string Work_Info_Notes, 
                    string Work_Info_Summary, 
                    System.Nullable<Work_Info_TypeType> Work_Info_Type, 
                    System.Nullable<System.DateTime> Work_Info_Date, 
                    System.Nullable<Work_Info_Communication_SourceType> Work_Info_Communication_Source, 
                    System.Nullable<Work_Info_LockedType> Work_Info_Locked, 
                    System.Nullable<Work_Info_View_AccessType> Work_Info_View_Access, 
                    string Resolution, 
                    string Cause, 
                    string Resolution_Method, 
                    string Resolution_Category_Tier_1, 
                    string Resolution_Category_Tier_2, 
                    string Resolution_Category_Tier_3, 
                    string Closure_Product_Category_Tier1, 
                    string Closure_Product_Category_Tier2, 
                    string Closure_Product_Category_Tier3, 
                    string Closure_Product_Name, 
                    string Closure_Product_Model_Version, 
                    string Closure_Manufacturer)
        {
            VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Resolve_IncidentRequest inValue = new VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Resolve_IncidentRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.Incident_Number = Incident_Number;
            inValue.Direct_Contact_Company = Direct_Contact_Company;
            inValue.Action_Status = Action_Status;
            inValue.InterfaceAction = InterfaceAction;
            inValue.Status = Status;
            inValue.Status_Reason = Status_Reason;
            inValue.Work_Info_Notes = Work_Info_Notes;
            inValue.Work_Info_Summary = Work_Info_Summary;
            inValue.Work_Info_Type = Work_Info_Type;
            inValue.Work_Info_Date = Work_Info_Date;
            inValue.Work_Info_Communication_Source = Work_Info_Communication_Source;
            inValue.Work_Info_Locked = Work_Info_Locked;
            inValue.Work_Info_View_Access = Work_Info_View_Access;
            inValue.Resolution = Resolution;
            inValue.Cause = Cause;
            inValue.Resolution_Method = Resolution_Method;
            inValue.Resolution_Category_Tier_1 = Resolution_Category_Tier_1;
            inValue.Resolution_Category_Tier_2 = Resolution_Category_Tier_2;
            inValue.Resolution_Category_Tier_3 = Resolution_Category_Tier_3;
            inValue.Closure_Product_Category_Tier1 = Closure_Product_Category_Tier1;
            inValue.Closure_Product_Category_Tier2 = Closure_Product_Category_Tier2;
            inValue.Closure_Product_Category_Tier3 = Closure_Product_Category_Tier3;
            inValue.Closure_Product_Name = Closure_Product_Name;
            inValue.Closure_Product_Model_Version = Closure_Product_Model_Version;
            inValue.Closure_Manufacturer = Closure_Manufacturer;
            return ((VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType)(this)).HelpDesk_Resolve_IncidentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Relate_CIResponse> VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType.HelpDesk_Relate_CIAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Relate_CIRequest request)
        {
            return base.Channel.HelpDesk_Relate_CIAsync(request);
        }
        
        public System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Relate_CIResponse> HelpDesk_Relate_CIAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo, string Incident_Number, string Direct_Contact_Company, string Action_Status, System.Nullable<InterfaceActionType> InterfaceAction, VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status, string CI_Name, string Lookup_Keyword)
        {
            VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Relate_CIRequest inValue = new VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Relate_CIRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.Incident_Number = Incident_Number;
            inValue.Direct_Contact_Company = Direct_Contact_Company;
            inValue.Action_Status = Action_Status;
            inValue.InterfaceAction = InterfaceAction;
            inValue.Status = Status;
            inValue.CI_Name = CI_Name;
            inValue.Lookup_Keyword = Lookup_Keyword;
            return ((VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType)(this)).HelpDesk_Relate_CIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Update_SummaryResponse> VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType.HelpDesk_Update_SummaryAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Update_SummaryRequest request)
        {
            return base.Channel.HelpDesk_Update_SummaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Update_SummaryResponse> HelpDesk_Update_SummaryAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo, string Incident_Number, string Direct_Contact_Company, string Action_Status, System.Nullable<InterfaceActionType> InterfaceAction, VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status, string Summary)
        {
            VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Update_SummaryRequest inValue = new VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Update_SummaryRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.Incident_Number = Incident_Number;
            inValue.Direct_Contact_Company = Direct_Contact_Company;
            inValue.Action_Status = Action_Status;
            inValue.InterfaceAction = InterfaceAction;
            inValue.Status = Status;
            inValue.Summary = Summary;
            return ((VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType)(this)).HelpDesk_Update_SummaryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Assign_IncidentResponse> VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType.HelpDesk_Assign_IncidentAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Assign_IncidentRequest request)
        {
            return base.Channel.HelpDesk_Assign_IncidentAsync(request);
        }
        
        public System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Assign_IncidentResponse> HelpDesk_Assign_IncidentAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo, string Incident_Number, string Direct_Contact_Company, string Action_Status, System.Nullable<InterfaceActionType> InterfaceAction, VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status, string Assigned_Support_Company, string Assigned_Support_Organization, string Assigned_Group, string Assignee)
        {
            VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Assign_IncidentRequest inValue = new VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Assign_IncidentRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.Incident_Number = Incident_Number;
            inValue.Direct_Contact_Company = Direct_Contact_Company;
            inValue.Action_Status = Action_Status;
            inValue.InterfaceAction = InterfaceAction;
            inValue.Status = Status;
            inValue.Assigned_Support_Company = Assigned_Support_Company;
            inValue.Assigned_Support_Organization = Assigned_Support_Organization;
            inValue.Assigned_Group = Assigned_Group;
            inValue.Assignee = Assignee;
            return ((VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType)(this)).HelpDesk_Assign_IncidentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Set_ProdCatResponse> VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType.HelpDesk_Set_ProdCatAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Set_ProdCatRequest request)
        {
            return base.Channel.HelpDesk_Set_ProdCatAsync(request);
        }
        
        public System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Set_ProdCatResponse> HelpDesk_Set_ProdCatAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo, string Incident_Number, string Direct_Contact_Company, string Action_Status, System.Nullable<InterfaceActionType> InterfaceAction, VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status, string Product_Categorization_Tier_1, string Product_Categorization_Tier_2, string Product_Categorization_Tier_3)
        {
            VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Set_ProdCatRequest inValue = new VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Set_ProdCatRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.Incident_Number = Incident_Number;
            inValue.Direct_Contact_Company = Direct_Contact_Company;
            inValue.Action_Status = Action_Status;
            inValue.InterfaceAction = InterfaceAction;
            inValue.Status = Status;
            inValue.Product_Categorization_Tier_1 = Product_Categorization_Tier_1;
            inValue.Product_Categorization_Tier_2 = Product_Categorization_Tier_2;
            inValue.Product_Categorization_Tier_3 = Product_Categorization_Tier_3;
            return ((VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType)(this)).HelpDesk_Set_ProdCatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Add_WorkInfoResponse> VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType.HelpDesk_Add_WorkInfoAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Add_WorkInfoRequest request)
        {
            return base.Channel.HelpDesk_Add_WorkInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Add_WorkInfoResponse> HelpDesk_Add_WorkInfoAsync(VFNZ_HPD_IncidentInterface_Mod_UAT.AuthenticationInfo AuthenticationInfo, string Incident_Number, string Action_Status, System.Nullable<InterfaceActionType> InterfaceAction, VFNZ_HPD_IncidentInterface_Mod_UAT.StatusType Status, string Work_Info_Notes, string Work_Info_Summary, System.Nullable<Work_Info_TypeType> Work_Info_Type, string Work_Info_Date, System.Nullable<Work_Info_Communication_SourceType> Work_Info_Communication_Source, System.Nullable<Work_Info_LockedType> Work_Info_Locked, System.Nullable<Work_Info_View_AccessType> Work_Info_View_Access)
        {
            VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Add_WorkInfoRequest inValue = new VFNZ_HPD_IncidentInterface_Mod_UAT.HelpDesk_Add_WorkInfoRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.Incident_Number = Incident_Number;
            inValue.Action_Status = Action_Status;
            inValue.InterfaceAction = InterfaceAction;
            inValue.Status = Status;
            inValue.Work_Info_Notes = Work_Info_Notes;
            inValue.Work_Info_Summary = Work_Info_Summary;
            inValue.Work_Info_Type = Work_Info_Type;
            inValue.Work_Info_Date = Work_Info_Date;
            inValue.Work_Info_Communication_Source = Work_Info_Communication_Source;
            inValue.Work_Info_Locked = Work_Info_Locked;
            inValue.Work_Info_View_Access = Work_Info_View_Access;
            return ((VFNZ_HPD_IncidentInterface_Mod_UAT.HPD_IncidentInterface_WSPortTypePortType)(this)).HelpDesk_Add_WorkInfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HPD_IncidentInterface_WSPortTypeSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HPD_IncidentInterface_WSPortTypeSoap))
            {
                return new System.ServiceModel.EndpointAddress(/* REMOVED */);
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HPD_IncidentInterface_WSPortTypePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.HPD_IncidentInterface_WSPortTypeSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HPD_IncidentInterface_WSPortTypePortTypeClient.GetEndpointAddress(EndpointConfiguration.HPD_IncidentInterface_WSPortTypeSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            HPD_IncidentInterface_WSPortTypeSoap,
        }
    }
}
