//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCL_HPD_WorkLog_UAT
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:TCL_HPD_WorkLog", ConfigurationName="TCL_HPD_WorkLog_UAT.TCL_HPD_WorkLogPortType")]
    public interface TCL_HPD_WorkLogPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TCL_HPD_WorkLog/OpCreate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TCL_HPD_WorkLog_UAT.OpCreateResponse> OpCreateAsync(TCL_HPD_WorkLog_UAT.OpCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TCL_HPD_WorkLog/OpGetList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TCL_HPD_WorkLog_UAT.OpGetListResponse> OpGetListAsync(TCL_HPD_WorkLog_UAT.OpGetListRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:TCL_HPD_WorkLog")]
    public partial class AuthenticationInfo
    {
        
        private string userNameField;
        
        private string passwordField;
        
        private string authenticationField;
        
        private string localeField;
        
        private string timeZoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string authentication
        {
            get
            {
                return this.authenticationField;
            }
            set
            {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string timeZone
        {
            get
            {
                return this.timeZoneField;
            }
            set
            {
                this.timeZoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:TCL_HPD_WorkLog")]
    public enum Work_Info_SourceType
    {
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        Phone,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Voice Mail")]
        VoiceMail,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Walk In")]
        WalkIn,
        
        /// <remarks/>
        Pager,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System Assignment")]
        SystemAssignment,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:TCL_HPD_WorkLog")]
    public enum Secure_Work_LogType
    {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:TCL_HPD_WorkLog")]
    public enum Work_Info_View_AccessType
    {
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        Public,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:TCL_HPD_WorkLog")]
    public enum Work_Info_TypeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- Customer Inbound -----")]
        CustomerInbound,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Communication")]
        CustomerCommunication,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Follow-up")]
        CustomerFollowup,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Status Update")]
        CustomerStatusUpdate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- Customer Outbound -----")]
        CustomerOutbound,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Closure Follow Up")]
        ClosureFollowUp,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Detail Clarification")]
        DetailClarification,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("General Information")]
        GeneralInformation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resolution Communications")]
        ResolutionCommunications,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Satisfaction Survey")]
        SatisfactionSurvey,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Status Update")]
        StatusUpdate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- General -----")]
        General,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Incident Task / Action")]
        IncidentTaskAction,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Problem Script")]
        ProblemScript,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Working Log")]
        WorkingLog,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Email System")]
        EmailSystem,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Paging System")]
        PagingSystem,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpCreate", WrapperNamespace="urn:TCL_HPD_WorkLog", IsWrapped=true)]
    public partial class OpCreateRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:TCL_HPD_WorkLog")]
        public TCL_HPD_WorkLog_UAT.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:TCL_HPD_WorkLog", Order=0)]
        public TCL_HPD_WorkLog_UAT.Work_Info_SourceType Work_Info_Source;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:TCL_HPD_WorkLog", Order=1)]
        public string Description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:TCL_HPD_WorkLog", Order=2)]
        public string Detailed_Description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:TCL_HPD_WorkLog", Order=3)]
        public string Incident_Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:TCL_HPD_WorkLog", Order=4)]
        public TCL_HPD_WorkLog_UAT.Secure_Work_LogType Secure_Work_Log;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:TCL_HPD_WorkLog", Order=5)]
        public TCL_HPD_WorkLog_UAT.Work_Info_View_AccessType Work_Info_View_Access;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:TCL_HPD_WorkLog", Order=6)]
        public System.DateTime Work_Log_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:TCL_HPD_WorkLog", Order=7)]
        public TCL_HPD_WorkLog_UAT.Work_Info_TypeType Work_Info_Type;
        
        public OpCreateRequest()
        {
        }
        
        public OpCreateRequest(TCL_HPD_WorkLog_UAT.AuthenticationInfo AuthenticationInfo, TCL_HPD_WorkLog_UAT.Work_Info_SourceType Work_Info_Source, string Description, string Detailed_Description, string Incident_Number, TCL_HPD_WorkLog_UAT.Secure_Work_LogType Secure_Work_Log, TCL_HPD_WorkLog_UAT.Work_Info_View_AccessType Work_Info_View_Access, System.DateTime Work_Log_Date, TCL_HPD_WorkLog_UAT.Work_Info_TypeType Work_Info_Type)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.Work_Info_Source = Work_Info_Source;
            this.Description = Description;
            this.Detailed_Description = Detailed_Description;
            this.Incident_Number = Incident_Number;
            this.Secure_Work_Log = Secure_Work_Log;
            this.Work_Info_View_Access = Work_Info_View_Access;
            this.Work_Log_Date = Work_Log_Date;
            this.Work_Info_Type = Work_Info_Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpCreateResponse", WrapperNamespace="urn:TCL_HPD_WorkLog", IsWrapped=true)]
    public partial class OpCreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:TCL_HPD_WorkLog", Order=0)]
        public string Work_Log_ID;
        
        public OpCreateResponse()
        {
        }
        
        public OpCreateResponse(string Work_Log_ID)
        {
            this.Work_Log_ID = Work_Log_ID;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:TCL_HPD_WorkLog")]
    public partial class OutputMappingGetListValues
    {
        
        private string assigned_GroupField;
        
        private string descriptionField;
        
        private string incident_NumberField;
        
        private Secure_Work_LogType secure_Work_logField;
        
        private StatusType statusField;
        
        private Work_Info_View_AccessType work_Info_View_AccessField;
        
        private string work_Log_IDField;
        
        private Work_Info_SourceType work_Info_SourceField;
        
        private System.DateTime work_Log_DateField;
        
        private string work_Log_SubmitterField;
        
        private string detailed_DescriptionField;
        
        private Work_Info_TypeType work_Info_TypeField;
        
        private System.DateTime submit_DateField;
        
        private string companyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Assigned_Group
        {
            get
            {
                return this.assigned_GroupField;
            }
            set
            {
                this.assigned_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Incident_Number
        {
            get
            {
                return this.incident_NumberField;
            }
            set
            {
                this.incident_NumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Secure_Work_LogType Secure_Work_log
        {
            get
            {
                return this.secure_Work_logField;
            }
            set
            {
                this.secure_Work_logField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public StatusType Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Work_Info_View_AccessType Work_Info_View_Access
        {
            get
            {
                return this.work_Info_View_AccessField;
            }
            set
            {
                this.work_Info_View_AccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Work_Log_ID
        {
            get
            {
                return this.work_Log_IDField;
            }
            set
            {
                this.work_Log_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Work_Info_SourceType Work_Info_Source
        {
            get
            {
                return this.work_Info_SourceField;
            }
            set
            {
                this.work_Info_SourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime Work_Log_Date
        {
            get
            {
                return this.work_Log_DateField;
            }
            set
            {
                this.work_Log_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Work_Log_Submitter
        {
            get
            {
                return this.work_Log_SubmitterField;
            }
            set
            {
                this.work_Log_SubmitterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Detailed_Description
        {
            get
            {
                return this.detailed_DescriptionField;
            }
            set
            {
                this.detailed_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Work_Info_TypeType Work_Info_Type
        {
            get
            {
                return this.work_Info_TypeField;
            }
            set
            {
                this.work_Info_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime Submit_Date
        {
            get
            {
                return this.submit_DateField;
            }
            set
            {
                this.submit_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:TCL_HPD_WorkLog")]
    public enum StatusType
    {
        
        /// <remarks/>
        Proposed,
        
        /// <remarks/>
        Enabled,
        
        /// <remarks/>
        Offline,
        
        /// <remarks/>
        Obsolete,
        
        /// <remarks/>
        Archive,
        
        /// <remarks/>
        Delete,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpGetList", WrapperNamespace="urn:TCL_HPD_WorkLog", IsWrapped=true)]
    public partial class OpGetListRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:TCL_HPD_WorkLog")]
        public TCL_HPD_WorkLog_UAT.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:TCL_HPD_WorkLog", Order=0)]
        public string Qualification;
        
        public OpGetListRequest()
        {
        }
        
        public OpGetListRequest(TCL_HPD_WorkLog_UAT.AuthenticationInfo AuthenticationInfo, string Qualification)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.Qualification = Qualification;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpGetListResponse", WrapperNamespace="urn:TCL_HPD_WorkLog", IsWrapped=true)]
    public partial class OpGetListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:TCL_HPD_WorkLog", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GetListValues")]
        public TCL_HPD_WorkLog_UAT.OutputMappingGetListValues[] GetListValues;
        
        public OpGetListResponse()
        {
        }
        
        public OpGetListResponse(TCL_HPD_WorkLog_UAT.OutputMappingGetListValues[] GetListValues)
        {
            this.GetListValues = GetListValues;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface TCL_HPD_WorkLogPortTypeChannel : TCL_HPD_WorkLog_UAT.TCL_HPD_WorkLogPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class TCL_HPD_WorkLogPortTypeClient : System.ServiceModel.ClientBase<TCL_HPD_WorkLog_UAT.TCL_HPD_WorkLogPortType>, TCL_HPD_WorkLog_UAT.TCL_HPD_WorkLogPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TCL_HPD_WorkLogPortTypeClient() : 
                base(TCL_HPD_WorkLogPortTypeClient.GetDefaultBinding(), TCL_HPD_WorkLogPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TCL_HPD_WorkLogSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TCL_HPD_WorkLogPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(TCL_HPD_WorkLogPortTypeClient.GetBindingForEndpoint(endpointConfiguration), TCL_HPD_WorkLogPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TCL_HPD_WorkLogPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TCL_HPD_WorkLogPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TCL_HPD_WorkLogPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TCL_HPD_WorkLogPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TCL_HPD_WorkLogPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCL_HPD_WorkLog_UAT.OpCreateResponse> TCL_HPD_WorkLog_UAT.TCL_HPD_WorkLogPortType.OpCreateAsync(TCL_HPD_WorkLog_UAT.OpCreateRequest request)
        {
            return base.Channel.OpCreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCL_HPD_WorkLog_UAT.OpCreateResponse> OpCreateAsync(TCL_HPD_WorkLog_UAT.AuthenticationInfo AuthenticationInfo, TCL_HPD_WorkLog_UAT.Work_Info_SourceType Work_Info_Source, string Description, string Detailed_Description, string Incident_Number, TCL_HPD_WorkLog_UAT.Secure_Work_LogType Secure_Work_Log, TCL_HPD_WorkLog_UAT.Work_Info_View_AccessType Work_Info_View_Access, System.DateTime Work_Log_Date, TCL_HPD_WorkLog_UAT.Work_Info_TypeType Work_Info_Type)
        {
            TCL_HPD_WorkLog_UAT.OpCreateRequest inValue = new TCL_HPD_WorkLog_UAT.OpCreateRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.Work_Info_Source = Work_Info_Source;
            inValue.Description = Description;
            inValue.Detailed_Description = Detailed_Description;
            inValue.Incident_Number = Incident_Number;
            inValue.Secure_Work_Log = Secure_Work_Log;
            inValue.Work_Info_View_Access = Work_Info_View_Access;
            inValue.Work_Log_Date = Work_Log_Date;
            inValue.Work_Info_Type = Work_Info_Type;
            return ((TCL_HPD_WorkLog_UAT.TCL_HPD_WorkLogPortType)(this)).OpCreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCL_HPD_WorkLog_UAT.OpGetListResponse> TCL_HPD_WorkLog_UAT.TCL_HPD_WorkLogPortType.OpGetListAsync(TCL_HPD_WorkLog_UAT.OpGetListRequest request)
        {
            return base.Channel.OpGetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCL_HPD_WorkLog_UAT.OpGetListResponse> OpGetListAsync(TCL_HPD_WorkLog_UAT.AuthenticationInfo AuthenticationInfo, string Qualification)
        {
            TCL_HPD_WorkLog_UAT.OpGetListRequest inValue = new TCL_HPD_WorkLog_UAT.OpGetListRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.Qualification = Qualification;
            return ((TCL_HPD_WorkLog_UAT.TCL_HPD_WorkLogPortType)(this)).OpGetListAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TCL_HPD_WorkLogSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TCL_HPD_WorkLogSoap))
            {
                return new System.ServiceModel.EndpointAddress(/* REMOVED */);
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TCL_HPD_WorkLogPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.TCL_HPD_WorkLogSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TCL_HPD_WorkLogPortTypeClient.GetEndpointAddress(EndpointConfiguration.TCL_HPD_WorkLogSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            TCL_HPD_WorkLogSoap,
        }
    }
}
