//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPD_IncidentInterface_UAT
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:HPD_IncidentInterface_WS", ConfigurationName="HPD_IncidentInterface_UAT.HPD_IncidentInterface_WSPortType")]
    public interface HPD_IncidentInterface_WSPortType
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:HPD_IncidentInterface_WS/HelpDesk_Query_Service", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HPD_IncidentInterface_UAT.HelpDesk_Query_ServiceResponse> HelpDesk_Query_ServiceAsync(HPD_IncidentInterface_UAT.HelpDesk_Query_ServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:HPD_IncidentInterface_WS/HelpDesk_QueryList_Service", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HPD_IncidentInterface_UAT.HelpDesk_QueryList_ServiceResponse> HelpDesk_QueryList_ServiceAsync(HPD_IncidentInterface_UAT.HelpDesk_QueryList_ServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:HPD_IncidentInterface_WS/HelpDesk_Modify_Service", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HPD_IncidentInterface_UAT.HelpDesk_Modify_ServiceResponse> HelpDesk_Modify_ServiceAsync(HPD_IncidentInterface_UAT.HelpDesk_Modify_ServiceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
    public partial class AuthenticationInfo
    {
        
        private string userNameField;
        
        private string passwordField;
        
        private string authenticationField;
        
        private string localeField;
        
        private string timeZoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string authentication
        {
            get
            {
                return this.authenticationField;
            }
            set
            {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string timeZone
        {
            get
            {
                return this.timeZoneField;
            }
            set
            {
                this.timeZoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
    public enum Contact_SensitivityType
    {
        
        /// <remarks/>
        Sensitive,
        
        /// <remarks/>
        Standard,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
    public enum ImpactType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1-Extensive/Widespread")]
        Item1ExtensiveWidespread,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2-Significant/Large")]
        Item2SignificantLarge,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3-Moderate/Limited")]
        Item3ModerateLimited,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4-Minor/Localized")]
        Item4MinorLocalized,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
    public enum PriorityType
    {
        
        /// <remarks/>
        Critical,
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Low,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
    public enum Reported_SourceType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Direct Input")]
        DirectInput,
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("External Escalation")]
        ExternalEscalation,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Systems Management")]
        SystemsManagement,
        
        /// <remarks/>
        Phone,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Voice Mail")]
        VoiceMail,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Walk In")]
        WalkIn,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
    public enum Service_TypeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("User Service Restoration")]
        UserServiceRestoration,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("User Service Request")]
        UserServiceRequest,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Restoration")]
        InfrastructureRestoration,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Event")]
        InfrastructureEvent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
    public enum StatusType
    {
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Assigned,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("In Progress")]
        InProgress,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Resolved,
        
        /// <remarks/>
        Closed,
        
        /// <remarks/>
        Cancelled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
    public enum Status_ReasonType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Change Created")]
        InfrastructureChangeCreated,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Local Site Action Required")]
        LocalSiteActionRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Purchase Order Approval")]
        PurchaseOrderApproval,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Registration Approval")]
        RegistrationApproval,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Supplier Delivery")]
        SupplierDelivery,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Support Contact Hold")]
        SupportContactHold,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Third Party Vendor Action Reqd")]
        ThirdPartyVendorActionReqd,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Client Action Required")]
        ClientActionRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Change")]
        InfrastructureChange,
        
        /// <remarks/>
        Request,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Future Enhancement")]
        FutureEnhancement,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pending Original Incident")]
        PendingOriginalIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Client Hold")]
        ClientHold,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Monitoring Incident")]
        MonitoringIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Follow-Up Required")]
        CustomerFollowUpRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Temporary Corrective Action")]
        TemporaryCorrectiveAction,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("No Further Action Required")]
        NoFurtherActionRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resolved by Original Incident")]
        ResolvedbyOriginalIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Automated Resolution Reported")]
        AutomatedResolutionReported,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("No longer a Causal CI")]
        NolongeraCausalCI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
    public enum UrgencyType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1-Critical")]
        Item1Critical,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2-High")]
        Item2High,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3-Medium")]
        Item3Medium,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4-Low")]
        Item4Low,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
    public enum VIPType
    {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Query_Service", WrapperNamespace="urn:HPD_IncidentInterface_WS", IsWrapped=true)]
    public partial class HelpDesk_Query_ServiceRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
        public HPD_IncidentInterface_UAT.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=0)]
        public string Incident_Number;
        
        public HelpDesk_Query_ServiceRequest()
        {
        }
        
        public HelpDesk_Query_ServiceRequest(HPD_IncidentInterface_UAT.AuthenticationInfo AuthenticationInfo, string Incident_Number)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.Incident_Number = Incident_Number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Query_ServiceResponse", WrapperNamespace="urn:HPD_IncidentInterface_WS", IsWrapped=true)]
    public partial class HelpDesk_Query_ServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=0)]
        public string Assigned_Group;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=1)]
        public string Assigned_Group_Shift_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=2)]
        public string Assigned_Support_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=3)]
        public string Assigned_Support_Organization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=4)]
        public string Assignee;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=5)]
        public string Categorization_Tier_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=6)]
        public string Categorization_Tier_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=7)]
        public string Categorization_Tier_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=8)]
        public string City;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=9)]
        public string Closure_Manufacturer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=10)]
        public string Closure_Product_Category_Tier1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=11)]
        public string Closure_Product_Category_Tier2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=12)]
        public string Closure_Product_Category_Tier3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=13)]
        public string Closure_Product_Model_Version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=14)]
        public string Closure_Product_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=15)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=16)]
        public string Contact_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=17)]
        public HPD_IncidentInterface_UAT.Contact_SensitivityType Contact_Sensitivity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=18)]
        public string Country;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=19)]
        public string Department;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=20)]
        public string Summary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=21)]
        public string Notes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=22)]
        public string First_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=23)]
        public HPD_IncidentInterface_UAT.ImpactType Impact;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=24)]
        public string Last_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=25)]
        public string Manufacturer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=26)]
        public string Middle_Initial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=27)]
        public string Organization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=28)]
        public string Phone_Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=29)]
        public HPD_IncidentInterface_UAT.PriorityType Priority;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=30)]
        public int Priority_Weight;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=31)]
        public string Product_Categorization_Tier_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=32)]
        public string Product_Categorization_Tier_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=33)]
        public string Product_Categorization_Tier_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=34)]
        public string Product_Model_Version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=35)]
        public string Product_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=36)]
        public string Region;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=37)]
        public HPD_IncidentInterface_UAT.Reported_SourceType Reported_Source;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=38)]
        public string Resolution;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=39)]
        public string Resolution_Category;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=40)]
        public string Resolution_Category_Tier_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=41)]
        public string Resolution_Category_Tier_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=42)]
        public HPD_IncidentInterface_UAT.Service_TypeType Service_Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=43)]
        public string Site;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=44)]
        public string Site_Group;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=45)]
        public HPD_IncidentInterface_UAT.StatusType Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=46)]
        public HPD_IncidentInterface_UAT.Status_ReasonType Status_Reason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=47)]
        public HPD_IncidentInterface_UAT.UrgencyType Urgency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=48)]
        public HPD_IncidentInterface_UAT.VIPType VIP;
        
        public HelpDesk_Query_ServiceResponse()
        {
        }
        
        public HelpDesk_Query_ServiceResponse(
                    string Assigned_Group, 
                    string Assigned_Group_Shift_Name, 
                    string Assigned_Support_Company, 
                    string Assigned_Support_Organization, 
                    string Assignee, 
                    string Categorization_Tier_1, 
                    string Categorization_Tier_2, 
                    string Categorization_Tier_3, 
                    string City, 
                    string Closure_Manufacturer, 
                    string Closure_Product_Category_Tier1, 
                    string Closure_Product_Category_Tier2, 
                    string Closure_Product_Category_Tier3, 
                    string Closure_Product_Model_Version, 
                    string Closure_Product_Name, 
                    string Company, 
                    string Contact_Company, 
                    HPD_IncidentInterface_UAT.Contact_SensitivityType Contact_Sensitivity, 
                    string Country, 
                    string Department, 
                    string Summary, 
                    string Notes, 
                    string First_Name, 
                    HPD_IncidentInterface_UAT.ImpactType Impact, 
                    string Last_Name, 
                    string Manufacturer, 
                    string Middle_Initial, 
                    string Organization, 
                    string Phone_Number, 
                    HPD_IncidentInterface_UAT.PriorityType Priority, 
                    int Priority_Weight, 
                    string Product_Categorization_Tier_1, 
                    string Product_Categorization_Tier_2, 
                    string Product_Categorization_Tier_3, 
                    string Product_Model_Version, 
                    string Product_Name, 
                    string Region, 
                    HPD_IncidentInterface_UAT.Reported_SourceType Reported_Source, 
                    string Resolution, 
                    string Resolution_Category, 
                    string Resolution_Category_Tier_2, 
                    string Resolution_Category_Tier_3, 
                    HPD_IncidentInterface_UAT.Service_TypeType Service_Type, 
                    string Site, 
                    string Site_Group, 
                    HPD_IncidentInterface_UAT.StatusType Status, 
                    HPD_IncidentInterface_UAT.Status_ReasonType Status_Reason, 
                    HPD_IncidentInterface_UAT.UrgencyType Urgency, 
                    HPD_IncidentInterface_UAT.VIPType VIP)
        {
            this.Assigned_Group = Assigned_Group;
            this.Assigned_Group_Shift_Name = Assigned_Group_Shift_Name;
            this.Assigned_Support_Company = Assigned_Support_Company;
            this.Assigned_Support_Organization = Assigned_Support_Organization;
            this.Assignee = Assignee;
            this.Categorization_Tier_1 = Categorization_Tier_1;
            this.Categorization_Tier_2 = Categorization_Tier_2;
            this.Categorization_Tier_3 = Categorization_Tier_3;
            this.City = City;
            this.Closure_Manufacturer = Closure_Manufacturer;
            this.Closure_Product_Category_Tier1 = Closure_Product_Category_Tier1;
            this.Closure_Product_Category_Tier2 = Closure_Product_Category_Tier2;
            this.Closure_Product_Category_Tier3 = Closure_Product_Category_Tier3;
            this.Closure_Product_Model_Version = Closure_Product_Model_Version;
            this.Closure_Product_Name = Closure_Product_Name;
            this.Company = Company;
            this.Contact_Company = Contact_Company;
            this.Contact_Sensitivity = Contact_Sensitivity;
            this.Country = Country;
            this.Department = Department;
            this.Summary = Summary;
            this.Notes = Notes;
            this.First_Name = First_Name;
            this.Impact = Impact;
            this.Last_Name = Last_Name;
            this.Manufacturer = Manufacturer;
            this.Middle_Initial = Middle_Initial;
            this.Organization = Organization;
            this.Phone_Number = Phone_Number;
            this.Priority = Priority;
            this.Priority_Weight = Priority_Weight;
            this.Product_Categorization_Tier_1 = Product_Categorization_Tier_1;
            this.Product_Categorization_Tier_2 = Product_Categorization_Tier_2;
            this.Product_Categorization_Tier_3 = Product_Categorization_Tier_3;
            this.Product_Model_Version = Product_Model_Version;
            this.Product_Name = Product_Name;
            this.Region = Region;
            this.Reported_Source = Reported_Source;
            this.Resolution = Resolution;
            this.Resolution_Category = Resolution_Category;
            this.Resolution_Category_Tier_2 = Resolution_Category_Tier_2;
            this.Resolution_Category_Tier_3 = Resolution_Category_Tier_3;
            this.Service_Type = Service_Type;
            this.Site = Site;
            this.Site_Group = Site_Group;
            this.Status = Status;
            this.Status_Reason = Status_Reason;
            this.Urgency = Urgency;
            this.VIP = VIP;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:HPD_IncidentInterface_WS")]
    public partial class GetListOutputMapGetListValues
    {
        
        private string assigned_GroupField;
        
        private string assigned_Group_Shift_NameField;
        
        private string assigned_Support_CompanyField;
        
        private string assigned_Support_OrganizationField;
        
        private string assigneeField;
        
        private string categorization_Tier_1Field;
        
        private string categorization_Tier_2Field;
        
        private string categorization_Tier_3Field;
        
        private string cityField;
        
        private string closure_ManufacturerField;
        
        private string closure_Product_Category_Tier1Field;
        
        private string closure_Product_Category_Tier2Field;
        
        private string closure_Product_Category_Tier3Field;
        
        private string closure_Product_Model_VersionField;
        
        private string closure_Product_NameField;
        
        private string companyField;
        
        private string contact_CompanyField;
        
        private Contact_SensitivityType contact_SensitivityField;
        
        private string countryField;
        
        private string departmentField;
        
        private string summaryField;
        
        private string notesField;
        
        private string first_NameField;
        
        private ImpactType impactField;
        
        private string incident_NumberField;
        
        private string internet_EmailField;
        
        private string last_NameField;
        
        private string manufacturerField;
        
        private string middle_InitialField;
        
        private string organizationField;
        
        private string phone_NumberField;
        
        private PriorityType priorityField;
        
        private int priority_WeightField;
        
        private string product_Categorization_Tier_1Field;
        
        private string product_Categorization_Tier_2Field;
        
        private string product_Categorization_Tier_3Field;
        
        private string product_Model_VersionField;
        
        private string product_NameField;
        
        private string regionField;
        
        private Reported_SourceType reported_SourceField;
        
        private string resolutionField;
        
        private string resolution_CategoryField;
        
        private string resolution_Category_Tier_2Field;
        
        private string resolution_Category_Tier_3Field;
        
        private Service_TypeType service_TypeField;
        
        private string siteField;
        
        private string site_GroupField;
        
        private StatusType statusField;
        
        private Status_ReasonType status_ReasonField;
        
        private UrgencyType urgencyField;
        
        private VIPType vIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Assigned_Group
        {
            get
            {
                return this.assigned_GroupField;
            }
            set
            {
                this.assigned_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Assigned_Group_Shift_Name
        {
            get
            {
                return this.assigned_Group_Shift_NameField;
            }
            set
            {
                this.assigned_Group_Shift_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Assigned_Support_Company
        {
            get
            {
                return this.assigned_Support_CompanyField;
            }
            set
            {
                this.assigned_Support_CompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Assigned_Support_Organization
        {
            get
            {
                return this.assigned_Support_OrganizationField;
            }
            set
            {
                this.assigned_Support_OrganizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Assignee
        {
            get
            {
                return this.assigneeField;
            }
            set
            {
                this.assigneeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Categorization_Tier_1
        {
            get
            {
                return this.categorization_Tier_1Field;
            }
            set
            {
                this.categorization_Tier_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Categorization_Tier_2
        {
            get
            {
                return this.categorization_Tier_2Field;
            }
            set
            {
                this.categorization_Tier_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Categorization_Tier_3
        {
            get
            {
                return this.categorization_Tier_3Field;
            }
            set
            {
                this.categorization_Tier_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Closure_Manufacturer
        {
            get
            {
                return this.closure_ManufacturerField;
            }
            set
            {
                this.closure_ManufacturerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Closure_Product_Category_Tier1
        {
            get
            {
                return this.closure_Product_Category_Tier1Field;
            }
            set
            {
                this.closure_Product_Category_Tier1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Closure_Product_Category_Tier2
        {
            get
            {
                return this.closure_Product_Category_Tier2Field;
            }
            set
            {
                this.closure_Product_Category_Tier2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Closure_Product_Category_Tier3
        {
            get
            {
                return this.closure_Product_Category_Tier3Field;
            }
            set
            {
                this.closure_Product_Category_Tier3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Closure_Product_Model_Version
        {
            get
            {
                return this.closure_Product_Model_VersionField;
            }
            set
            {
                this.closure_Product_Model_VersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Closure_Product_Name
        {
            get
            {
                return this.closure_Product_NameField;
            }
            set
            {
                this.closure_Product_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Contact_Company
        {
            get
            {
                return this.contact_CompanyField;
            }
            set
            {
                this.contact_CompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public Contact_SensitivityType Contact_Sensitivity
        {
            get
            {
                return this.contact_SensitivityField;
            }
            set
            {
                this.contact_SensitivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string First_Name
        {
            get
            {
                return this.first_NameField;
            }
            set
            {
                this.first_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public ImpactType Impact
        {
            get
            {
                return this.impactField;
            }
            set
            {
                this.impactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Incident_Number
        {
            get
            {
                return this.incident_NumberField;
            }
            set
            {
                this.incident_NumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Internet_E-mail", Order=25)]
        public string Internet_Email
        {
            get
            {
                return this.internet_EmailField;
            }
            set
            {
                this.internet_EmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Last_Name
        {
            get
            {
                return this.last_NameField;
            }
            set
            {
                this.last_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Manufacturer
        {
            get
            {
                return this.manufacturerField;
            }
            set
            {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Middle_Initial
        {
            get
            {
                return this.middle_InitialField;
            }
            set
            {
                this.middle_InitialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Phone_Number
        {
            get
            {
                return this.phone_NumberField;
            }
            set
            {
                this.phone_NumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public PriorityType Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public int Priority_Weight
        {
            get
            {
                return this.priority_WeightField;
            }
            set
            {
                this.priority_WeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string Product_Categorization_Tier_1
        {
            get
            {
                return this.product_Categorization_Tier_1Field;
            }
            set
            {
                this.product_Categorization_Tier_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string Product_Categorization_Tier_2
        {
            get
            {
                return this.product_Categorization_Tier_2Field;
            }
            set
            {
                this.product_Categorization_Tier_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string Product_Categorization_Tier_3
        {
            get
            {
                return this.product_Categorization_Tier_3Field;
            }
            set
            {
                this.product_Categorization_Tier_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string Product_Model_Version
        {
            get
            {
                return this.product_Model_VersionField;
            }
            set
            {
                this.product_Model_VersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string Product_Name
        {
            get
            {
                return this.product_NameField;
            }
            set
            {
                this.product_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public Reported_SourceType Reported_Source
        {
            get
            {
                return this.reported_SourceField;
            }
            set
            {
                this.reported_SourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string Resolution
        {
            get
            {
                return this.resolutionField;
            }
            set
            {
                this.resolutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string Resolution_Category
        {
            get
            {
                return this.resolution_CategoryField;
            }
            set
            {
                this.resolution_CategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string Resolution_Category_Tier_2
        {
            get
            {
                return this.resolution_Category_Tier_2Field;
            }
            set
            {
                this.resolution_Category_Tier_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string Resolution_Category_Tier_3
        {
            get
            {
                return this.resolution_Category_Tier_3Field;
            }
            set
            {
                this.resolution_Category_Tier_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public Service_TypeType Service_Type
        {
            get
            {
                return this.service_TypeField;
            }
            set
            {
                this.service_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string Site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string Site_Group
        {
            get
            {
                return this.site_GroupField;
            }
            set
            {
                this.site_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public StatusType Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public Status_ReasonType Status_Reason
        {
            get
            {
                return this.status_ReasonField;
            }
            set
            {
                this.status_ReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public UrgencyType Urgency
        {
            get
            {
                return this.urgencyField;
            }
            set
            {
                this.urgencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public VIPType VIP
        {
            get
            {
                return this.vIPField;
            }
            set
            {
                this.vIPField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_QueryList_Service", WrapperNamespace="urn:HPD_IncidentInterface_WS", IsWrapped=true)]
    public partial class HelpDesk_QueryList_ServiceRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
        public HPD_IncidentInterface_UAT.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=0)]
        public string Qualification;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=1)]
        public string startRecord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=2)]
        public string maxLimit;
        
        public HelpDesk_QueryList_ServiceRequest()
        {
        }
        
        public HelpDesk_QueryList_ServiceRequest(HPD_IncidentInterface_UAT.AuthenticationInfo AuthenticationInfo, string Qualification, string startRecord, string maxLimit)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.Qualification = Qualification;
            this.startRecord = startRecord;
            this.maxLimit = maxLimit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_QueryList_ServiceResponse", WrapperNamespace="urn:HPD_IncidentInterface_WS", IsWrapped=true)]
    public partial class HelpDesk_QueryList_ServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getListValues")]
        public HPD_IncidentInterface_UAT.GetListOutputMapGetListValues[] getListValues;
        
        public HelpDesk_QueryList_ServiceResponse()
        {
        }
        
        public HelpDesk_QueryList_ServiceResponse(HPD_IncidentInterface_UAT.GetListOutputMapGetListValues[] getListValues)
        {
            this.getListValues = getListValues;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
    public enum Work_Info_TypeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- Customer Inbound -----")]
        CustomerInbound,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Communication")]
        CustomerCommunication,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Follow-up")]
        CustomerFollowup,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Status Update")]
        CustomerStatusUpdate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- Customer Outbound -----")]
        CustomerOutbound,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Closure Follow Up")]
        ClosureFollowUp,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Detail Clarification")]
        DetailClarification,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("General Information")]
        GeneralInformation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resolution Communications")]
        ResolutionCommunications,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Satisfaction Survey")]
        SatisfactionSurvey,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Status Update")]
        StatusUpdate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- General -----")]
        General,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Incident Task / Action")]
        IncidentTaskAction,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Problem Script")]
        ProblemScript,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Working Log")]
        WorkingLog,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Email System")]
        EmailSystem,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Paging System")]
        PagingSystem,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
    public enum Work_Info_SourceType
    {
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        Phone,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Voice Mail")]
        VoiceMail,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Walk In")]
        WalkIn,
        
        /// <remarks/>
        Pager,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System Assignment")]
        SystemAssignment,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
    public enum Work_Info_View_AccessType
    {
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        Public,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Modify_Service", WrapperNamespace="urn:HPD_IncidentInterface_WS", IsWrapped=true)]
    public partial class HelpDesk_Modify_ServiceRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:HPD_IncidentInterface_WS")]
        public HPD_IncidentInterface_UAT.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=0)]
        public string Categorization_Tier_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=1)]
        public string Categorization_Tier_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=2)]
        public string Categorization_Tier_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=3)]
        public string Closure_Manufacturer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=4)]
        public string Closure_Product_Category_Tier1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=5)]
        public string Closure_Product_Category_Tier2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=6)]
        public string Closure_Product_Category_Tier3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=7)]
        public string Closure_Product_Model_Version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=8)]
        public string Closure_Product_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=9)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=10)]
        public string Summary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=11)]
        public string Notes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=12)]
        public HPD_IncidentInterface_UAT.ImpactType Impact;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=13)]
        public string Manufacturer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=14)]
        public string Product_Categorization_Tier_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=15)]
        public string Product_Categorization_Tier_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=16)]
        public string Product_Categorization_Tier_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=17)]
        public string Product_Model_Version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=18)]
        public string Product_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=19)]
        public HPD_IncidentInterface_UAT.Reported_SourceType Reported_Source;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=20)]
        public string Resolution;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=21)]
        public string Resolution_Category;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=22)]
        public string Resolution_Category_Tier_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=23)]
        public string Resolution_Category_Tier_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=24)]
        public string Resolution_Method;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=25)]
        public HPD_IncidentInterface_UAT.Service_TypeType Service_Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=26)]
        public HPD_IncidentInterface_UAT.StatusType Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=27)]
        public HPD_IncidentInterface_UAT.UrgencyType Urgency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=28)]
        public string Action;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=29)]
        public string Work_Info_Summary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=30)]
        public string Work_Info_Notes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=31)]
        public System.Nullable<HPD_IncidentInterface_UAT.Work_Info_TypeType> Work_Info_Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=32)]
        public System.Nullable<System.DateTime> Work_Info_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=33)]
        public System.Nullable<HPD_IncidentInterface_UAT.Work_Info_SourceType> Work_Info_Source;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=34)]
        public System.Nullable<HPD_IncidentInterface_UAT.VIPType> Work_Info_Locked;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=35)]
        public System.Nullable<HPD_IncidentInterface_UAT.Work_Info_View_AccessType> Work_Info_View_Access;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_WS", Order=36)]
        public string Incident_Number;
        
        public HelpDesk_Modify_ServiceRequest()
        {
        }
        
        public HelpDesk_Modify_ServiceRequest(
                    HPD_IncidentInterface_UAT.AuthenticationInfo AuthenticationInfo, 
                    string Categorization_Tier_1, 
                    string Categorization_Tier_2, 
                    string Categorization_Tier_3, 
                    string Closure_Manufacturer, 
                    string Closure_Product_Category_Tier1, 
                    string Closure_Product_Category_Tier2, 
                    string Closure_Product_Category_Tier3, 
                    string Closure_Product_Model_Version, 
                    string Closure_Product_Name, 
                    string Company, 
                    string Summary, 
                    string Notes, 
                    HPD_IncidentInterface_UAT.ImpactType Impact, 
                    string Manufacturer, 
                    string Product_Categorization_Tier_1, 
                    string Product_Categorization_Tier_2, 
                    string Product_Categorization_Tier_3, 
                    string Product_Model_Version, 
                    string Product_Name, 
                    HPD_IncidentInterface_UAT.Reported_SourceType Reported_Source, 
                    string Resolution, 
                    string Resolution_Category, 
                    string Resolution_Category_Tier_2, 
                    string Resolution_Category_Tier_3, 
                    string Resolution_Method, 
                    HPD_IncidentInterface_UAT.Service_TypeType Service_Type, 
                    HPD_IncidentInterface_UAT.StatusType Status, 
                    HPD_IncidentInterface_UAT.UrgencyType Urgency, 
                    string Action, 
                    string Work_Info_Summary, 
                    string Work_Info_Notes, 
                    HPD_IncidentInterface_UAT.Work_Info_TypeType Work_Info_Type, 
                    System.DateTime Work_Info_Date, 
                    HPD_IncidentInterface_UAT.Work_Info_SourceType Work_Info_Source, 
                    HPD_IncidentInterface_UAT.VIPType Work_Info_Locked, 
                    HPD_IncidentInterface_UAT.Work_Info_View_AccessType Work_Info_View_Access, 
                    string Incident_Number)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.Categorization_Tier_1 = Categorization_Tier_1;
            this.Categorization_Tier_2 = Categorization_Tier_2;
            this.Categorization_Tier_3 = Categorization_Tier_3;
            this.Closure_Manufacturer = Closure_Manufacturer;
            this.Closure_Product_Category_Tier1 = Closure_Product_Category_Tier1;
            this.Closure_Product_Category_Tier2 = Closure_Product_Category_Tier2;
            this.Closure_Product_Category_Tier3 = Closure_Product_Category_Tier3;
            this.Closure_Product_Model_Version = Closure_Product_Model_Version;
            this.Closure_Product_Name = Closure_Product_Name;
            this.Company = Company;
            this.Summary = Summary;
            this.Notes = Notes;
            this.Impact = Impact;
            this.Manufacturer = Manufacturer;
            this.Product_Categorization_Tier_1 = Product_Categorization_Tier_1;
            this.Product_Categorization_Tier_2 = Product_Categorization_Tier_2;
            this.Product_Categorization_Tier_3 = Product_Categorization_Tier_3;
            this.Product_Model_Version = Product_Model_Version;
            this.Product_Name = Product_Name;
            this.Reported_Source = Reported_Source;
            this.Resolution = Resolution;
            this.Resolution_Category = Resolution_Category;
            this.Resolution_Category_Tier_2 = Resolution_Category_Tier_2;
            this.Resolution_Category_Tier_3 = Resolution_Category_Tier_3;
            this.Resolution_Method = Resolution_Method;
            this.Service_Type = Service_Type;
            this.Status = Status;
            this.Urgency = Urgency;
            this.Action = Action;
            this.Work_Info_Summary = Work_Info_Summary;
            this.Work_Info_Notes = Work_Info_Notes;
            this.Work_Info_Type = Work_Info_Type;
            this.Work_Info_Date = Work_Info_Date;
            this.Work_Info_Source = Work_Info_Source;
            this.Work_Info_Locked = Work_Info_Locked;
            this.Work_Info_View_Access = Work_Info_View_Access;
            this.Incident_Number = Incident_Number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Modify_ServiceResponse", WrapperNamespace="urn:HPD_IncidentInterface_WS", IsWrapped=true)]
    public partial class HelpDesk_Modify_ServiceResponse
    {
        
        public HelpDesk_Modify_ServiceResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface HPD_IncidentInterface_WSPortTypeChannel : HPD_IncidentInterface_UAT.HPD_IncidentInterface_WSPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class HPD_IncidentInterface_WSPortTypeClient : System.ServiceModel.ClientBase<HPD_IncidentInterface_UAT.HPD_IncidentInterface_WSPortType>, HPD_IncidentInterface_UAT.HPD_IncidentInterface_WSPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HPD_IncidentInterface_WSPortTypeClient() : 
                base(HPD_IncidentInterface_WSPortTypeClient.GetDefaultBinding(), HPD_IncidentInterface_WSPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.HPD_IncidentInterface_WSSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HPD_IncidentInterface_WSPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(HPD_IncidentInterface_WSPortTypeClient.GetBindingForEndpoint(endpointConfiguration), HPD_IncidentInterface_WSPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HPD_IncidentInterface_WSPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HPD_IncidentInterface_WSPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HPD_IncidentInterface_WSPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HPD_IncidentInterface_WSPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HPD_IncidentInterface_WSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<HPD_IncidentInterface_UAT.HelpDesk_Query_ServiceResponse> HelpDesk_Query_ServiceAsync(HPD_IncidentInterface_UAT.HelpDesk_Query_ServiceRequest request)
        {
            return base.Channel.HelpDesk_Query_ServiceAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HPD_IncidentInterface_UAT.HelpDesk_QueryList_ServiceResponse> HPD_IncidentInterface_UAT.HPD_IncidentInterface_WSPortType.HelpDesk_QueryList_ServiceAsync(HPD_IncidentInterface_UAT.HelpDesk_QueryList_ServiceRequest request)
        {
            return base.Channel.HelpDesk_QueryList_ServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<HPD_IncidentInterface_UAT.HelpDesk_QueryList_ServiceResponse> HelpDesk_QueryList_ServiceAsync(HPD_IncidentInterface_UAT.AuthenticationInfo AuthenticationInfo, string Qualification, string startRecord, string maxLimit)
        {
            HPD_IncidentInterface_UAT.HelpDesk_QueryList_ServiceRequest inValue = new HPD_IncidentInterface_UAT.HelpDesk_QueryList_ServiceRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.Qualification = Qualification;
            inValue.startRecord = startRecord;
            inValue.maxLimit = maxLimit;
            return ((HPD_IncidentInterface_UAT.HPD_IncidentInterface_WSPortType)(this)).HelpDesk_QueryList_ServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HPD_IncidentInterface_UAT.HelpDesk_Modify_ServiceResponse> HPD_IncidentInterface_UAT.HPD_IncidentInterface_WSPortType.HelpDesk_Modify_ServiceAsync(HPD_IncidentInterface_UAT.HelpDesk_Modify_ServiceRequest request)
        {
            return base.Channel.HelpDesk_Modify_ServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<HPD_IncidentInterface_UAT.HelpDesk_Modify_ServiceResponse> HelpDesk_Modify_ServiceAsync(
                    HPD_IncidentInterface_UAT.AuthenticationInfo AuthenticationInfo, 
                    string Categorization_Tier_1, 
                    string Categorization_Tier_2, 
                    string Categorization_Tier_3, 
                    string Closure_Manufacturer, 
                    string Closure_Product_Category_Tier1, 
                    string Closure_Product_Category_Tier2, 
                    string Closure_Product_Category_Tier3, 
                    string Closure_Product_Model_Version, 
                    string Closure_Product_Name, 
                    string Company, 
                    string Summary, 
                    string Notes, 
                    HPD_IncidentInterface_UAT.ImpactType Impact, 
                    string Manufacturer, 
                    string Product_Categorization_Tier_1, 
                    string Product_Categorization_Tier_2, 
                    string Product_Categorization_Tier_3, 
                    string Product_Model_Version, 
                    string Product_Name, 
                    HPD_IncidentInterface_UAT.Reported_SourceType Reported_Source, 
                    string Resolution, 
                    string Resolution_Category, 
                    string Resolution_Category_Tier_2, 
                    string Resolution_Category_Tier_3, 
                    string Resolution_Method, 
                    HPD_IncidentInterface_UAT.Service_TypeType Service_Type, 
                    HPD_IncidentInterface_UAT.StatusType Status, 
                    HPD_IncidentInterface_UAT.UrgencyType Urgency, 
                    string Action, 
                    string Work_Info_Summary, 
                    string Work_Info_Notes, 
                    HPD_IncidentInterface_UAT.Work_Info_TypeType? Work_Info_Type, 
                    System.DateTime? Work_Info_Date, 
                    HPD_IncidentInterface_UAT.Work_Info_SourceType? Work_Info_Source, 
                    HPD_IncidentInterface_UAT.VIPType? Work_Info_Locked, 
                    HPD_IncidentInterface_UAT.Work_Info_View_AccessType? Work_Info_View_Access, 
                    string Incident_Number)
        {
            HPD_IncidentInterface_UAT.HelpDesk_Modify_ServiceRequest inValue = new HPD_IncidentInterface_UAT.HelpDesk_Modify_ServiceRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.Categorization_Tier_1 = Categorization_Tier_1;
            inValue.Categorization_Tier_2 = Categorization_Tier_2;
            inValue.Categorization_Tier_3 = Categorization_Tier_3;
            inValue.Closure_Manufacturer = Closure_Manufacturer;
            inValue.Closure_Product_Category_Tier1 = Closure_Product_Category_Tier1;
            inValue.Closure_Product_Category_Tier2 = Closure_Product_Category_Tier2;
            inValue.Closure_Product_Category_Tier3 = Closure_Product_Category_Tier3;
            inValue.Closure_Product_Model_Version = Closure_Product_Model_Version;
            inValue.Closure_Product_Name = Closure_Product_Name;
            inValue.Company = Company;
            inValue.Summary = Summary;
            inValue.Notes = Notes;
            inValue.Impact = Impact;
            inValue.Manufacturer = Manufacturer;
            inValue.Product_Categorization_Tier_1 = Product_Categorization_Tier_1;
            inValue.Product_Categorization_Tier_2 = Product_Categorization_Tier_2;
            inValue.Product_Categorization_Tier_3 = Product_Categorization_Tier_3;
            inValue.Product_Model_Version = Product_Model_Version;
            inValue.Product_Name = Product_Name;
            inValue.Reported_Source = Reported_Source;
            inValue.Resolution = Resolution;
            inValue.Resolution_Category = Resolution_Category;
            inValue.Resolution_Category_Tier_2 = Resolution_Category_Tier_2;
            inValue.Resolution_Category_Tier_3 = Resolution_Category_Tier_3;
            inValue.Resolution_Method = Resolution_Method;
            inValue.Service_Type = Service_Type;
            inValue.Status = Status;
            inValue.Urgency = Urgency;
            inValue.Action = Action;
            inValue.Work_Info_Summary = Work_Info_Summary;
            inValue.Work_Info_Notes = Work_Info_Notes;
            inValue.Work_Info_Type = Work_Info_Type;
            inValue.Work_Info_Date = Work_Info_Date;
            inValue.Work_Info_Source = Work_Info_Source;
            inValue.Work_Info_Locked = Work_Info_Locked;
            inValue.Work_Info_View_Access = Work_Info_View_Access;
            inValue.Incident_Number = Incident_Number;
            return ((HPD_IncidentInterface_UAT.HPD_IncidentInterface_WSPortType)(this)).HelpDesk_Modify_ServiceAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HPD_IncidentInterface_WSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HPD_IncidentInterface_WSSoap))
            {
                return new System.ServiceModel.EndpointAddress(/* REMOVED */);
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HPD_IncidentInterface_WSPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.HPD_IncidentInterface_WSSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HPD_IncidentInterface_WSPortTypeClient.GetEndpointAddress(EndpointConfiguration.HPD_IncidentInterface_WSSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            HPD_IncidentInterface_WSSoap,
        }
    }
}
